name: CI
on: [push]

jobs:
  build-os-python:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.11", "3.13"]
    steps:
    - uses: actions/checkout@v3
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.43.3
        cache: true
        auth-host: prefix.dev
        auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
    - name: ruff
      run: |
        pixi run ruff
    - name: mypy
      if: success() || failure()
      run: |
        pixi run mypy
    - name: Test with pytest
      if: success() || failure()
      run: |
        pixi run coverage
