name: CI
on: [push]

jobs:
  build-os-python:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.11", "3.13"]
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        miniforge-version: latest
        conda-version: ">=24.11"
        conda-build-version: ">=25.1"
        environment-file: environment.yml
        activate-environment: mkxref-dev
        python-version: ${{ matrix.python-version }}
        condarc-file: github-condarc.yml
        auto-activate-base: true
        use-mamba: true
    - name: Dev install package
      run: |
        conda run -n mkxref-dev pip install -e . --no-deps --no-build-isolation
    - name: ruff
      run: |
        make ruff
    - name: mypy
      if: success() || failure()
      run: |
        make mypy
    - name: Test with pytest
      if: success() || failure()
      run: |
        make coverage-test
